### PR TITLE
Using array_key_exists() on objects is deprecated in PHP 7.4

### PR DESCRIPTION
**Pull request by bradleybensmith**
See https://www.php.net/manual/en/migration74.deprecated.php

### CODE REVIEW

**Comment by romanzipp** [comment]
@Elhebert Could you please review this PR? This issue makes php 7.4 usage impossible.

**Comment by mirorauhala** [comment]
I upgraded PHP to 7.4 already. Have to stop using laravel-sri until this fix is merged.

**Comment by Elhebert** [comment]
Sorry, it took a long time for me to merge this PR.

I don't use this package anymore and the notifications were "hidden" due to notifications coming from private repo's.

I'll try to be more careful when removing notifications in bulk.

**Comment by Elhebert** [comment]
Released as [2.0.2](https://github.com/Elhebert/laravel-sri/tree/2.0.2)

**Comment by mirorauhala** [comment]
**Thank you!**

**Pull request merged**
