### PR TITLE
 Add support for Laravel 5.8 

### PR DESCRIPTION
**Pull request by owenvoke**

### CODE REVIEW

**Comment by owenvoke** [comment]
Would you also be able to publish a new version with this at some point?

Cheers!

**Comment by Elhebert** [comment]
I'll do that tomorrow morning 👌

**Comment by Elhebert** [comment]
@pxgamer I published the [1.5.0](https://github.com/Elhebert/laravel-sri/releases/tag/1.5.0)

**Comment by owenvoke** [comment]
Great! Thanks @Elhebert

**Pull request merged**
